#!/bin/bash

# Создание базы данных, пользователя и таблиц
echo "Создание базы данных, пользователя и таблиц в MariaDB..."
mysql -u root <<EOF
CREATE DATABASE IF NOT EXISTS SERVERMANAGER;
CREATE USER IF NOT EXISTS 'SERVERMANAGER'@'localhost' IDENTIFIED BY 'SUPERPASSWORD';
GRANT ALL PRIVILEGES ON SERVERMANAGER.* TO 'SERVERMANAGER'@'localhost';
FLUSH PRIVILEGES;

USE SERVERMANAGER;

CREATE TABLE IF NOT EXISTS servers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    cpu INT NOT NULL,
    ram INT NOT NULL,
    ssd INT NOT NULL,
    hdd INT NOT NULL,
    deleted BOOLEAN DEFAULT FALSE,         -- Поле для логического удаления
    pending_delete BOOLEAN DEFAULT FALSE   -- Поле для ожидания удаления
);

CREATE TABLE IF NOT EXISTS virtual_machines (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    cpu INT NOT NULL,
    ram INT NOT NULL,
    ssd INT NOT NULL,
    hdd INT NOT NULL,
    server_id INT NOT NULL,
    deleted BOOLEAN DEFAULT FALSE,         -- Поле для логического удаления
    pending_delete BOOLEAN DEFAULT FALSE,  -- Поле для ожидания удаления
    FOREIGN KEY (server_id) REFERENCES servers(id)
);
EOF

# Установка Gunicorn через pipx
echo "Установка Gunicorn через pipx..."
pipx install gunicorn

# Создание виртуального окружения для приложения и установка зависимостей
echo "Создание виртуального окружения и установка зависимостей..."
python3 -m venv /opt/servers-mangment/venv
/opt/servers-mangment/venv/bin/pip install flask pymysql gunicorn

# Запуск systemd-сервиса
systemctl enable servers-managment.service
systemctl start servers-managment.service
